### ISSUE TITLE
[Camera] Capturing an image causes a crash

### ISSUE THREAD

**Issue by DelphiWorlds** [DelphiWorlds/Kastri#24]
As per summary, capturing an image causes a crash, with the following log:

```
19-11 05:40:28.711	W	com.embarcadero.CameraDemo	9541	9568	System.err	android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
19-11 05:40:28.711	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8798)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1606)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.view.View.requestLayout(View.java:25390)
19-11 05:40:28.712	I	com.embarcadero.CameraDemo	9541	9568	chatty	uid=10579(com.embarcadero.CameraDemo) CameraPreview identical 1 line
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.view.View.requestLayout(View.java:25390)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.view.ViewGroup.removeView(ViewGroup.java:5463)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at com.embarcadero.rtl.ProxyInterface.dispatchToNative(Native Method)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at com.embarcadero.rtl.ProxyInterface.invoke(ProxyInterface.java:21)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at $Proxy21.onImageAvailable(Unknown Source)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:812)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.os.Handler.dispatchMessage(Handler.java:106)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.os.Looper.loop(Looper.java:223)
19-11 05:40:28.712	W	com.embarcadero.CameraDemo	9541	9568	System.err	at android.os.HandlerThread.run(HandlerThread.java:67)
```

The issue is being worked on

**Comment by DelphiWorlds** [comment]
Commenting out a couple of lines in the demo seems to alleviate the issue:

```
procedure TCameraView.CameraImageCapturedHandler(Sender: TObject; const AImageStream: TStream);
begin
//  FImageStream.Clear;
//  FImageStream.CopyFrom(AImageStream, AImageStream.Size);
//  FCaptureImage.LoadFromStream(FImageStream);
  FCaptureImage.LoadFromStream(AImageStream);
  TabControl.ActiveTab := CaptureTab;
  EnableButtons(True);
  FAcceptImage.Visible := True;
  FCameraSwapImage.Visible := False;
end;
```

But this still needs to be resolved

**Comment by DelphiWorlds** [comment]
Fixed
